networks:
    redis-network:
        driver: bridge

services:
  bot:
    build: .
    env_file:
      -  .env
    volumes:
      - .:/Harper
    depends_on:
      - redis-db
    networks:
      - redis-network

  redis-db:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network

volumes:
  redis:
  redis-config: